- setup.cfg
> DM-35199: Fix python package names

- .github/workflows/build.yaml
> DM-35598: Run build workflow on tag

- .github/workflows/build.yaml
> DM-35598-hotfix: Fix quotes in PyPi upload GHA

- .github/workflows/build.yaml
- .github/workflows/docstyle.yaml
- .github/workflows/yamllint.yaml
- .pre-commit-config.yaml
- .yamllint.yaml
- MANIFEST.in
- README.rst
- doc/changes/DM-29575.feature.rst
- doc/changes/DM-29614.feature.rst
- doc/changes/DM-32047.feature.rst
- doc/changes/DM-32968.misc.rst
- doc/changes/DM-33887.bugfix.rst
- doc/changes/DM-33887.misc.rst
- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
- doc/lsst.ctrl.bps.htcondor/index.rst
- pyproject.toml
- setup.cfg
> DM-36034: v24.0.0 release notes

- README.rst
- doc/changes/DM-29575.feature.rst
- doc/changes/DM-29614.feature.rst
- doc/changes/DM-32047.feature.rst
- doc/changes/DM-32968.misc.rst
- doc/changes/DM-33887.bugfix.rst
- doc/changes/DM-33887.misc.rst
- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
- doc/lsst.ctrl.bps.htcondor/index.rst
- pyproject.toml
> DM-36034: Copy v24.0.0 release notes to main

- .github/workflows/build.yaml
- .pre-commit-config.yaml
- pyproject.toml
> DM-36174: Require Python 3.10.

- .pre-commit-config.yaml
- doc/conf.py
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
> DM-37808: Update pre-commit dependencies

- .pre-commit-config.yaml
- doc/changes/DM-35533.misc.rst
- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
- pyproject.toml
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- requirements.txt
> DM-38065: v25 release notes

- doc/changes/DM-35533.misc.rst
- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
> DM-38065: v25 release notes on main

- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- doc/conf.py
- pyproject.toml
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/htcondor/lssthtc.py
- tests/test_lssthtc.py
> DM-39857: Stop using pytest-flake8 and add ruff configuration

- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
- pyproject.toml
- requirements.txt
> DM-40883: Add v26 release notes

- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
- pyproject.toml
> DM-40883 (main): Add v26 release notes

- .github/workflows/build.yaml
- .github/workflows/do_not_merge.yaml
- .pre-commit-config.yaml
- pyproject.toml
> DM-41897: Drop python 3.10

- .github/workflows/build.yaml
- .github/workflows/rebase_checker.yaml
- pyproject.toml
> DM-41904: Add python 3.12 to list

- .pre-commit-config.yaml
- pyproject.toml
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/htcondor/lssthtc.py
> DM-42116: Add numpydoc validation

- doc/changes/DM-43721.bugfix.rst
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
> DM-43721: Fix compute_site keyword error in submit.

- .github/workflows/build.yaml
- doc/changes/DM-38627.feature.rst
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/htcondor/lssthtc.py
- tests/test_htcondor_service.py
> DM-38627: ctrl_bps_htcondor futile job reporting

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .github/workflows/do_not_merge.yaml
- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- doc/changes/DM-37020.misc.rst
- doc/changes/DM-37231.feature.rst
- doc/changes/DM-38627.feature.rst
- doc/changes/DM-40906.bugfix.rst
- doc/changes/DM-41561.feature.rst
- doc/changes/DM-42127.feature.rst
- doc/changes/DM-42759.misc.rst
- doc/changes/DM-43381.bugfix.rst
- doc/changes/DM-43721.bugfix.rst
- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
- pyproject.toml
- requirements.txt
> DM-44569: v27 release notes (on release branch)

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .github/workflows/do_not_merge.yaml
- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- doc/changes/DM-37020.misc.rst
- doc/changes/DM-37231.feature.rst
- doc/changes/DM-38627.feature.rst
- doc/changes/DM-40906.bugfix.rst
- doc/changes/DM-41561.feature.rst
- doc/changes/DM-42127.feature.rst
- doc/changes/DM-42759.misc.rst
- doc/changes/DM-43381.bugfix.rst
- doc/changes/DM-43721.bugfix.rst
- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
- pyproject.toml
- requirements.txt
> DM-44569: v27 release notes

- doc/changes/DM-44110.misc.rst
- python/lsst/ctrl/bps/htcondor/etc/htcondor_defaults.yaml
- python/lsst/ctrl/bps/htcondor/htcondor_config.py
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- tests/test_htcondor_service.py
> DM-44110: Add ability for WMS-specific default configs

- doc/changes/DM-44457.misc.rst
- doc/lsst.ctrl.bps.htcondor/userguide.rst
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- tests/test_htcondor_service.py
> DM-44457: Fix held and deleted state_counts for reporting.

- doc/changes/DM-35145.feature.rst
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- tests/test_htcondor_service.py
> DM-35145: Implement basic ping method for HTCondor plugin.

- doc/changes/DM-45654.misc.rst
- python/lsst/ctrl/bps/htcondor/lssthtc.py
- tests/data/good.dag
- tests/test_lssthtc.py
> DM-45654: Update to allow spaces in job submit file path.

- doc/changes/DM-46046.misc.rst
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- tests/test_htcondor_service.py
> DM-46046: Update bps restart to work with relative path.

- doc/changes/DM-38538.doc.rst
- doc/lsst.ctrl.bps.htcondor/userguide.rst
> DM-38538: Describe how to release held jobs in ctrl_bps_htcondor docs

- doc/changes/DM-35145.feature.rst
- doc/changes/DM-38538.doc.rst
- doc/changes/DM-42579.feature.rst
- doc/changes/DM-43932.misc.rst
- doc/changes/DM-44107.bugfix.rst
- doc/changes/DM-44110.misc.rst
- doc/changes/DM-44457.misc.rst
- doc/changes/DM-44668.bugfix.rst
- doc/changes/DM-44668.feature.rst
- doc/changes/DM-45654.misc.rst
- doc/changes/DM-46046.misc.rst
- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
- requirements.txt
> DM-47673: v28 release notes

- python/lsst/ctrl/bps/htcondor/htcondor_service.py
> DM-48785: Reformat code using new black formatter

- doc/changes/DM-46307.misc.rst
- doc/changes/DM-48032.bugfix.rst
- doc/changes/DM-48245.feature.rst
- doc/changes/DM-48752.misc.rst
- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
- requirements.txt
> DM-49674 (v29): v29 release notes

- .pre-commit-config.yaml
- doc/changes/DM-46307.misc.rst
- doc/changes/DM-48032.bugfix.rst
- doc/changes/DM-48245.feature.rst
- doc/changes/DM-48752.misc.rst
- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
> DM-49674: v29 release notes

- doc/changes/DM-50614.feature.rst
- doc/lsst.ctrl.bps.htcondor/userguide.rst
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- tests/test_htcondor_service.py
> DM-50614: Add ability to add job release expression.

- doc/changes/DM-50619.feature.rst
- doc/lsst.ctrl.bps.htcondor/userguide.rst
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/htcondor/lssthtc.py
- tests/test_htcondor_service.py
> DM-50619: Add quick status method to HTCondorService class.

- .github/workflows/build_docs.yaml
- doc/changes/DM-46294.feature.rst
- doc/changes/DM-50212.misc.rst
- doc/changes/DM-50614.feature.rst
- doc/changes/DM-50619.feature.rst
- doc/lsst.ctrl.bps.htcondor/CHANGES.rst
> DM-51073: v29.1 release notes

- doc/changes/DM-31879.other.rst
- python/lsst/ctrl/bps/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/htcondor/lssthtc.py
- python/lsst/ctrl/bps/htcondor/provisioner.py
- tests/test_htcondor_service.py
- tests/test_lssthtc.py
- tests/test_provisioner.py
> DM-31879: Reduce number of files created by bps HTCondor plugin
